Travis HDF5: 1.10.1
Stay with HDF5 1.10.1 instead of 1.10.2 on Travis.

Building parallel HDF5 itself fails with

```
H5Dmpio.c:3027:17: error: use of undeclared identifier 'MPI_Message'
     1064                    MPI_Message message;
```

in the latest HDF5 release.