C++14 (#825)
* C++14

Require C++14 or newer.

* Remove Pre-C++14 #ifdefs

* More -Wno-deprecated-declarations

* pybind11: refactor variant caster

* GCC 5.0: Add visit_helper for Variant

Try to address:
```
In file included from /home/runner/work/openPMD-api/openPMD-api/include/openPMD/binding/python/Variant.hpp:26:0,
                 from /home/runner/work/openPMD-api/openPMD-api/include/openPMD/binding/python/Numpy.hpp:24,
                 from /home/runner/work/openPMD-api/openPMD-api/src/binding/python/Attributable.cpp:24:
/home/runner/work/openPMD-api/openPMD-api/share/openPMD/thirdParty/pybind11/include/pybind11/stl.h: In instantiation of ‘static pybind11::handle pybind11::detail::variant_caster<V<Ts ...> >::cast(Variant&&, pybind11::return_value_policy, pybind11::handle) [with Variant = mpark::variant ...
 /home/runner/work/openPMD-api/openPMD-api/src/binding/python/Attributable.cpp:337:10:   required from here
/home/runner/work/openPMD-api/openPMD-api/share/openPMD/thirdParty/pybind11/include/pybind11/stl.h:362:37: error: no matching function for call to ‘pybind11::detail::visit_helper<mpark::variant>::call(pybind11::detail::variant_caster_visitor, mpark::variant<
```

* Visual Studio: 2017+

Too old for multi-return statements in constexpr functions:
  MSVC++ 14.0, _MSC_VER == 1900 (Visual Studio 2015 version 14.0)

New enough:
  MSVC++ 14.1, _MSC_VER == 1910 (Visual Studio 2017 version 15.0)

* AppVeyor: Diversify VS & Py Versions

* GH Action: Cache