RTD: Limit Sphinx to <4.0
Update from sphinx-3.5.4 to -4.0.1 broke our RTD builds:

```
  File "/home/docs/checkouts/readthedocs.org/user_builds/openpmd-api/envs/latest/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py", line 96, in DomainDirectiveFactory
    'function': (python.PyModulelevel, 'function'),
AttributeError: module 'sphinx.domains.python' has no attribute 'PyModulelevel'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/openpmd-api/envs/latest/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py", line 96, in DomainDirectiveFactory
    'function': (python.PyModulelevel, 'function'),
AttributeError: module 'sphinx.domains.python' has no attribute 'PyModulelevel'
```