macOS: PyPy (Polyfit), hdf5-mpi
PyPI on macOS-10.15:
```
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned
```

For OpenMPI builds we can also use the brew hdf5-mpi package
that we contributed :)