Warnings: Unreachable Code & Unused Param (#1053)
* Test 8b: Fix unused parameter

On non-Linux:
```
examples/8b_benchmark_read_parallel.cpp:59:47: error: unused parameter 'tag' [-Werror,-Wunused-parameter]
  MemoryProfiler(int rank, const std::string& tag) {
                                              ^
1 error generated.
```

* Datatype: Remove unreachable statements

Spotted by NVHPC compilation