macOS PyPy: OpenBLAS for Numpy
For issue:
```
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, more information is available at https://numpy.org/doc/stable/user/building.html#accelerated-blas-lapack-libraries Otherwise report this to the vendor that provided NumPy.
```
Since PyPy builds a new numpy wheel on the fly.

https://github.com/numpy/numpy/issues/15947#issuecomment-686164134