Release 0.14.4 backports (#1177)
* Add `cmake/` to MANIFEST.in

Forgot to add in #1128, which is then missing in Python sdist files
for pip from-source builds.

* Add failing test

* Read gridSpacing also from long doubles

* Python: 3.10

Add support for Python 3.10.

* CI: Python 3.10 on Alpine Linux

musllinux uses the musl libc on an Alpine stack, especially for
docker-ish containers.

Let's add coverage while also covering CPython 3.10

* Fix: Python Iteration Repr Typo

Fix a typo in the `__repr__` of `Iteration` in Python.

* Remove invalid records from our data structure entirely

Until now, the half-parsed records were not deleted.
Our sanity checks in `Series::~Series()` caught up on that and threw
errors.

* Fix doxygen?

No idea why this PR triggers that error

* Don't apply compression operators multipe times

Happened so far in variable-based iteration encoding

* ICC 19.1.2: CXX17 Work-Arounds (Variant)

The `Attribute` constructors with implicit variant conversion
sometimes do not work in ICC 19.1.2.

```
openPMD-api/src/RecordComponent.cpp(226): error: no instance of constructor "openPMD::Attribute::Attribute" matches the argument list
            argument types are: (openPMD::Extent)
                  Attribute a(getExtent());
                              ^
openPMD-api/include/openPMD/backend/Attribute.hpp(50): note: this candidate was rejected because arguments do not match
  class Attribute :
        ^
openPMD-api/include/openPMD/backend/Attribute.hpp(50): note: this candidate was rejected because arguments do not match
  class Attribute :
        ^
openPMD-api/include/openPMD/backend/Attribute.hpp(79): note: this candidate was rejected because arguments do not match
      Attribute(resource r) : Variant(std::move(r))
      ^
```

Same work-around as for NVCC in  #1103

* CMake 3.22+: Policy CMP0127

Fix a warning with CMake 3.22+.

We use simple syntax in cmake_dependent_option, so we are compatible
with the extended syntax in CMake 3.22+:
  https://cmake.org/cmake/help/v3.22/policy/CMP0127.html

* Docs: Minor Warnings

Fix minor warnings in the docs:
- double reference (make 2nd ref annonymous)
- misaligned reference

* Docs: Fix HDF5 JSON File

Fix misnamed filename and misnamed prefix in text.

* Docs: Update Citation & Add BibTeX

Add `.bib` blocks for easier citation of standard and API.

* Docs: Fix CLI Highlighting

Fix a highlighting issue for `openPMD-ls` in the docs.
Explicitly use `python3` for module calls.

* CMake: Warning Flags First in CXXFLAGS

If we append them, then we overwrite flags like `-Wno-...` from
environment variables.

* ADIOS2 fixes: Incompatibilites w/ `master`

Referes to post-`2.7.1` `master` branch of ADIOS2.

Catch new ADIOS2 error type: string

getCompressionOperator

Dirtily catch ADIOS2 exception in automatically_deactivate_span

Cleanly destruct a Series that errored during flushing

Problem was that IO tasks that do not return cleanly but throw an
exception must be removed from the IO queue, otherwise the task will be
tried again during destruction. Usually, this means that anything will
happen.

SerialIOTest: Remove Comments (resolved)

Print warning when removing task from IO queue

std::string and fix warning

* Automatically deactivate span-based API when operators are present

* Add .pre-commit-config.yaml

* Release: 0.14.4

Co-authored-by: Franz Pöschel <franz.poeschel@gmail.com>