GCC 5.0: Add visit_helper for Variant
Try to address:
```
In file included from /home/runner/work/openPMD-api/openPMD-api/include/openPMD/binding/python/Variant.hpp:26:0,
                 from /home/runner/work/openPMD-api/openPMD-api/include/openPMD/binding/python/Numpy.hpp:24,
                 from /home/runner/work/openPMD-api/openPMD-api/src/binding/python/Attributable.cpp:24:
/home/runner/work/openPMD-api/openPMD-api/share/openPMD/thirdParty/pybind11/include/pybind11/stl.h: In instantiation of ‘static pybind11::handle pybind11::detail::variant_caster<V<Ts ...> >::cast(Variant&&, pybind11::return_value_policy, pybind11::handle) [with Variant = mpark::variant ...
 /home/runner/work/openPMD-api/openPMD-api/src/binding/python/Attributable.cpp:337:10:   required from here
/home/runner/work/openPMD-api/openPMD-api/share/openPMD/thirdParty/pybind11/include/pybind11/stl.h:362:37: error: no matching function for call to ‘pybind11::detail::visit_helper<mpark::variant>::call(pybind11::detail::variant_caster_visitor, mpark::variant<
```