Clang 6: `-Wno-ignored-attributes -Wno-unused-const-variable`
clang-6 has a false positive on `src/auxiliary/Filesystem.cpp`
with `-Wno-ignored-attributes`:
```C++
[[maybe_unused]] MPI_Datatype const MPI_Types< unsigned >::value = MPI_UNSIGNED;
```

Adding only `-Wno-ignored-attributes` then leads to:
```
src/auxiliary/Filesystem.cpp:201:47: error: unused variable 'value' [-Werror,-Wunused-const-variable]
    MPI_Datatype const MPI_Types< unsigned >::value = MPI_UNSIGNED;
                                              ^
```