CoreTest: Lambda outside uneval context (#1057)
Fix:
```
openPMD-api/test/CoreTest.cpp", line 25:
  error: a lambda is not allowed in an unevaluated expression
  REQUIRE(2u == std::count_if(apiVersion.begin(), apiVersion.end(),
                              []( char const c ){ return c == '.';}));
```
seen with NVHPC