HDF5 Dask DataFrame issue: File ID
When removing those lines - and only with HDF5 - I get the following
error on `electrons.to_dask()`:
```
openpmd_api/DaskDataFrame.py in particles_to_daskdataframe(particle_species)
     65         for k_rc, rc in r.items():
     66             if not rc.constant:
---> 67                 chunks = rc.available_chunks()
     68                 break
     69         if chunks:

RuntimeError: [HDF5] File ID not found with file name
```

Seen with the 3D openPMD HDF5 example data set, at iteration 400.
Printing the records and components in the loop shows:
- charge Scalar (skipped because constant)
- mass Scalar (skipped because constant)
- momentum x (calls available_chunks)